export const categories = [
  { name: 'Audio', count: '48 pieces', icon: '◉', color: 'bg-[#e8e1ff]' },
  { name: 'Wearables', count: '32 pieces', icon: '⌁', color: 'bg-[#d9ff64]' },
  { name: 'Workspace', count: '64 pieces', icon: '⌨', color: 'bg-[#dff4ff]' },
  { name: 'Home', count: '41 pieces', icon: '⌂', color: 'bg-[#ffe4d6]' },
]

export const products = [
  {
    id: 1,
    name: 'Arc One Headphones',
    category: 'Immersive audio',
    description: 'Adaptive noise control, all-day comfort, and a clean sound signature for focused listening.',
    price: 349,
    rating: 4.9,
    reviews: 128,
    color: '#e2e6ee',
    accent: '#3159ff',
    image: '/products/arc-one.webp',
    badge: 'Bestseller',
  },
  {
    id: 2,
    name: 'Halo Smart Ring',
    category: 'Health & wellness',
    description: 'A lightweight daily tracker built for sleep, recovery, and low-profile wear.',
    price: 219,
    rating: 4.8,
    reviews: 86,
    color: '#16171b',
    accent: '#d9ff64',
    image: '/products/halo-ring.webp',
    badge: 'New',
  },
  {
    id: 3,
    name: 'Form Mechanical Keys',
    category: 'Workspace',
    description: 'A tactile mechanical keyboard with a compact footprint and soft acoustic tuning.',
    price: 189,
    rating: 4.7,
    reviews: 214,
    color: '#e9dfd4',
    accent: '#fd734e',
    image: '/products/form-keys.webp',
  },
  {
    id: 4,
    name: 'Aura Ambient Light',
    category: 'Smart home',
    description: 'A dimmable accent lamp with warm tones and a minimal footprint for desks and shelves.',
    price: 129,
    rating: 4.9,
    reviews: 57,
    color: '#dcd4ff',
    accent: '#7758ff',
    image: '/products/aura-light.webp',
    badge: 'Editor’s pick',
  },
  {
    id: 5,
    name: 'Mono Field Watch',
    category: 'Wearables',
    description: 'A durable field watch with a clean face, balanced proportions, and everyday reliability.',
    price: 279,
    rating: 4.8,
    reviews: 92,
    color: '#d9e2de',
    accent: '#143d31',
    image: '/products/mono-watch.webp',
  },
  {
    id: 6,
    name: 'Drift Pocket Speaker',
    category: 'Portable audio',
    description: 'A compact speaker with surprising output, travel-ready power, and quick pairing.',
    price: 99,
    rating: 4.6,
    reviews: 173,
    color: '#e5e5e5',
    accent: '#ff5b3d',
    image: '/products/drift-speaker.webp',
  },
]

export const testimonials = [
  {
    quote: 'Aether feels like having a design-obsessed friend curate the internet for you. Everything I’ve ordered has earned its place.',
    name: 'Maya Chen',
    role: 'Creative Director',
    initials: 'MC',
  },
  {
    quote: 'The rare store where the experience is as considered as the products. Fast, calm, and genuinely delightful.',
    name: 'Noah Williams',
    role: 'Product Designer',
    initials: 'NW',
  },
  {
    quote: 'Their recommendations are unusually spot-on. I found my entire desk setup in under ten minutes.',
    name: 'Priya Rao',
    role: 'Founder, Fieldnote',
    initials: 'PR',
  },
]
